{"number": 2600, "ref": "fix-async-from-sync-close", "login": "mhofman", "head": "f3c4d29fc2bfb6b5579d0a6921cd2383413f9bf0", "base": "a2da384e5577aa3c4e423c5f2535a44a94551376", "title": "Normative: Close sync iterator when async wrapper yields rejection", "created_at": "2021-12-17T02:56:25Z", "updated_at": "2021-12-21T18:56:20Z", "revs": [{"hash": "f3c4d29fc2bfb6b5579d0a6921cd2383413f9bf0", "parents": "9da23ec28efcad53708540842ddc7626eaef57fc", "author": "Mathieu Hofman", "date": "2021-12-21T18:55:28+00:00", "adate": "2021-12-20T23:26:57+00:00", "subject": "Do not close when iterator has already been requested closed"}, {"hash": "9da23ec28efcad53708540842ddc7626eaef57fc", "parents": "1937798149243e406b644cd7289bbdaa7980ac13", "author": "Mathieu Hofman", "date": "2021-12-17T19:09:43+00:00", "adate": "2021-12-17T19:09:43+00:00", "subject": "Close iterator if not done, regardless of action type Close iterator on buggy promise value"}, {"hash": "1937798149243e406b644cd7289bbdaa7980ac13", "parents": "92262e309fe9492c6f8e0134ff3568ea1e75538b", "author": "Mathieu Hofman", "date": "2021-12-17T04:37:56+00:00", "adate": "2021-12-17T04:37:56+00:00", "subject": "fix: do not close a done iterator"}, {"hash": "92262e309fe9492c6f8e0134ff3568ea1e75538b", "parents": "012af13cb8d7ba78a3125086a2cd9059a1f8a4e8", "author": "Mathieu Hofman", "date": "2021-12-17T03:06:44+00:00", "adate": "2021-12-17T02:22:37+00:00", "subject": "Normative: Close sync iterator when async wrapper yields rejection"}]}