{"number": 2683, "ref": "fix-async-generator-assertion", "login": "tc39", "head": "9e725c9a679f8f1b78de144e85b00487ab59529b", "base": "cbd5493ae4d0ad72e4e658e47764638c025c2edf", "title": "Normative: handle broken promises in AsyncGenerator.prototype.return", "created_at": "2022-03-05T04:30:05Z", "updated_at": "2022-03-05T04:34:47Z", "revs": [{"hash": "9e725c9a679f8f1b78de144e85b00487ab59529b", "parents": "c691b9e911375e8f2f4f2c1b9d50db5d60c7c379", "author": "Kevin Gibbons", "date": "2022-03-04T19:15:20-08:00", "adate": "2022-03-04T19:14:36-08:00", "subject": "Editorial: AsyncGeneratorAwaitReturn does not throw"}, {"hash": "c691b9e911375e8f2f4f2c1b9d50db5d60c7c379", "parents": "cbd5493ae4d0ad72e4e658e47764638c025c2edf", "author": "Kevin Gibbons", "date": "2022-03-04T19:15:19-08:00", "adate": "2022-03-04T19:12:24-08:00", "subject": "Normative: handle broken promises in AsyncGenerator.prototype.return"}]}